sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: W94oRTw9A3dQxz2yx5BkhFhCUTvSeMSaaTXemtLKtNQ+I6N2z4XcntZTCRSsLQq3IaOQaC+qz9NjxDBSLGKVxi+Orz4O9XbnZAMnIJjbxxLadBSSPrC5ubb9rIiPOskz/PGr9s/LsKjCXLj/6UKH+E1DPAh+r+7RvDUl3u8QpLkoCNLdPcnJFTi7FZzGCjy/8joSBOOqJH/7YsTdavtQvS/iBQEOeP1NkChGn4uHeG81B7Hx2J9cO5J6JpqR+DjMjgujaA1jw+te/NsVTe//qEApzm/XUZT9x/h91S95tEkMfAMjeaHibiH2akAnuQKEyeZRBLeqmafeFm4P+NoeAumvxOjy36nK5Ti8rj0EvN45+IfqGLIhVxS7/2jZq/M3iGoxUt7z944y24h8xc/T9kMp6MVYhxiyJ/hBUIQrtZ/r/p0aaoyNuHt3BksKKQwxD1mLvQJbHzSWGWUhQAM8rweh3WaDcSmLaNjPxw3CUgSMycRPUorSrHmb/PztVLqYUlHobAr3hHiecNVOOzpQULB0UxY/J73X89c8rcpv/68Bcz6TzVi+tNeocwelPxDf3Shj8LaGehAo/hOj4GN+ds5S+UtEUXngdgiKY7+KX7X4oJHxlcfA5V+iJgHn+Qf/NE30AD2nQbpG+mgOg/cbU1t4aM7hiDJtFAdl3LJjB78=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Life-of-Charlotte-Bront----Volume-2_1700
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy